package com.csc.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;

import com.csc.CurrentSession;
import com.csc.model.FoodPreference;

/**
 *
 * @author twinklesiva05
 */
public class PreferencesPanel extends javax.swing.JPanel {

   JLabel jLabel5;
	public PreferencesPanel(JLabel remainingFundsLabel) {
		initComponents();
		this.jLabel5=remainingFundsLabel;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jButton1 = new javax.swing.JButton();

		jCheckBox1.setText("Low Sodium");

		jTextField1.setText("jTextField1");

		jLabel1.setText("Enter Calorie Requirement/day");

		jCheckBox2.setText("Low Fat");
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jCheckBox3.setText("Low Cheese");

		jButton1.setText("Save");
		
		jButton1.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int calories=Integer.parseInt(jTextField1.getText());
				FoodPreference preference=new FoodPreference(CurrentSession.getCurrentUser().getCardNumber());
			    preference.save(calories);
			    jLabel5.setText("Remaining Calories:"+preference.getRemainingCalories());
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jButton1)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(36, 36, 36)
												.addComponent(jLabel1)
												.addGap(40, 40, 40)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addGap(28, 28, 28)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jCheckBox1)
																.addComponent(jCheckBox2)
																.addComponent(jCheckBox3)))))
																.addContainerGap(48, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(51, 51, 51)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
								.addGap(18, 18, 18)
								.addComponent(jCheckBox1)
								.addGap(18, 18, 18)
								.addComponent(jCheckBox2)
								.addGap(18, 18, 18)
								.addComponent(jCheckBox3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
								.addComponent(jButton1)
								.addGap(38, 38, 38))
				);
	}// </editor-fold>                        

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
	}                                          


	// Variables declaration - do not modify                     
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration                   
}                

